services:
  # Web service for the .NET API
  - type: web
    name: bilgelojistik-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/BilgeLojistikIK.API/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: bilgelojistik-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
      - key: ADDITIONAL_CORS_ORIGINS
        value: https://your-app-git-main.vercel.app

# PostgreSQL database
databases:
  - name: bilgelojistik-db
    databaseName: bilgelojistikikdb
    user: bilgelojistik
    plan: free